### PR TITLE
Rename 6to5 to babel

### PR DESCRIPTION
**Pull request by zertosh**
Hey @STRML, we changed the name of 6to5 to babel. I'm waiting on https://github.com/wbond/package_control_channel/pull/4099 before I merge https://github.com/6to5/6to5-sublime/pull/38. So, I'll ping you again when this PR should be merged. Thank you!

### CODE REVIEW

**Comment by zertosh** [comment]
@STRML, we're all set... please merge :smile:

**Comment by poteto** [comment]
:+1:

**Comment by STRML** [comment]
@zertosh The two PRs you sent me conflict, could you fix it up?

**Comment by STRML** [comment]
Also, I don't see the harm in leaving the `Javascript 6to5` definition in for a few versions, in case users have manually installed a syntax or some other issue prevents them from upgrading sublimelinter-jsxhint and their syntax definitions at the same time.

**Comment by zertosh** [comment]
@STRML, just rebased, but yeah let me do another one... you're right about the leaving 6to5

**Comment by zertosh** [comment]
@STRML done!

**Comment by STRML** [comment]
Thanks - for whatever reason I didn't get an email for your changes, but :+1: - looks great.

**Pull request merged**
